// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: w63X2LqEPLNaKe4vMByZM4

import * as React from "react";
import { hasVariant, ensureGlobalVariants } from "@plasmicapp/react-web";
import { ThemeProvider } from "lido-plasmic/plasmic-provider/components"; // plasmic-import: ehgcCPxh5-/codeComponent
import { ReefKnotProvider } from "lido-plasmic/plasmic-provider/components"; // plasmic-import: wFzKexUD_xN/codeComponent

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  themeProviderProps?: Partial<
    Omit<React.ComponentProps<typeof ThemeProvider>, "children">
  >;

  reefKnotProviderProps?: Partial<
    Omit<React.ComponentProps<typeof ReefKnotProvider>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, themeProviderProps, reefKnotProviderProps } = props;

  console.log(props);

  return (
    <ThemeProvider
      {...themeProviderProps}
      useSystemTheme={
        themeProviderProps && "useSystemTheme" in themeProviderProps
          ? themeProviderProps.useSystemTheme!
          : true
      }
    >
      <ReefKnotProvider
        {...reefKnotProviderProps}
        network={
          reefKnotProviderProps && "network" in reefKnotProviderProps
            ? reefKnotProviderProps.network!
            : ["mainnet"]
        }
      >
        {children}
      </ReefKnotProvider>
    </ThemeProvider>
  );
}
