
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: w63X2LqEPLNaKe4vMByZM4

    

    import * as React from "react"
    import {hasVariant, ensureGlobalVariants} from "@plasmicapp/react-web";
    import { CompqYq0AmZ9FQs } from "./CompqYq0AmZ9FQs";  // plasmic-import: qYQ0AmZ9FQs/codeComponent
import { CompehgcCPxh5 } from "./CompehgcCPxh5";  // plasmic-import: ehgcCPxh5-/codeComponent
    

    export interface GlobalContextsProviderProps {
      children?: React.ReactElement;
      wagmiProps?: Partial<
           Omit<React.ComponentProps<typeof CompqYq0AmZ9FQs>, "children">>;
themeProps?: Partial<
           Omit<React.ComponentProps<typeof CompehgcCPxh5>, "children">>;
    }

    export default function GlobalContextsProvider(props: GlobalContextsProviderProps) {
      
      const {
        children,
        wagmiProps,
themeProps
      } = props;

      
      return (
      <CompqYq0AmZ9FQs
      {...wagmiProps}
      network={(wagmiProps && "network" in wagmiProps) ? wagmiProps.network! : ["mainnet"]}
      >
        
      <CompehgcCPxh5
      {...themeProps}
      useSystemTheme={(themeProps && "useSystemTheme" in themeProps) ? themeProps.useSystemTheme! : true}
      >
        { children }
      </CompehgcCPxh5>
    
      </CompqYq0AmZ9FQs>
    )
    }
  